
// for individual file upload
// status are idle => setted => start uploading => uploaded or error
  export const SET_INDIVIDUAL_UPLOAD_FILE = "SET_INDIVIDUAL_UPLOAD_FILE";
  export const START_INDIVIDUAL_UPLOADING_FILE = "START_INDIVIDUAL_UPLOADING_FILE";
  export const SET_INDIVIDUAL_UPLOAD_PROGRESS = "SET_INDIVIDUAL_UPLOAD_PROGRESS";
  export const SUCCESS_INDIVIDUAL_UPLOAD_FILE = "SUCCESS_INDIVIDUAL_UPLOAD_FILE";
  export const FAILURE_INDIVIDUAL_UPLOAD_FILE = "FAILURE_INDIVIDUAL_UPLOAD_FILE";
  export const ERROR_INDIVIDUAL_UPLOAD_FILE = "ERROR_INDIVIDUAL_UPLOAD_FILE";
  
  // for team file upload
// status are idle => setted => start uploading => uploaded or error
export const SET_TEAM_UPLOAD_FILE = "SET_TEAM_UPLOAD_FILE";
export const START_TEAM_UPLOADING_FILE = "START_TEAM_UPLOADING_FILE";
export const SET_TEAM_UPLOAD_PROGRESS = "SET_TEAM_UPLOAD_PROGRESS";
export const SUCCESS_TEAM_UPLOAD_FILE = "SUCCESS_TEAM_UPLOAD_FILE";
export const FAILURE_TEAM_UPLOAD_FILE = "FAILURE_TEAM_UPLOAD_FILE";
export const ERROR_TEAM_UPLOAD_FILE = "ERROR_TEAM_UPLOAD_FILE";
