
// for individual idea submission
// status are checking => loading => success or failed or error 
export const INDIVIDUAL_SUBMISSION_CHECKING = "INDIVIDUAL_SUBMISSION_CHECKING";
export const INDIVIDUAL_SUBMISSION_LOADING = "INDIVIDUAL_SUBMISSION_LOADING";
export const INDIVIDUAL_SUBMISSION_SUCCESS = "INDIVIDUAL_SUBMISSION_SUCCESS";
export const INDIVIDUAL_SUBMISSION_FAILED = "INDIVIDUAL_SUBMISSION_FAILED";
export const INDIVIDUAL_SUBMISSION_ERROR = "INDIVIDUAL_SUBMISSION_ERROR";


// for team idea submission
// status are checking => loading => success or failed or error 
export const TEAM_SUBMISSION_CHECKING = "TEAM_SUBMISSION_CHECKING";
export const TEAM_SUBMISSION_LOADING = "TEAM_SUBMISSION_LOADING";
export const TEAM_SUBMISSION_SUCCESS = "TEAM_SUBMISSION_SUCCESS";
export const TEAM_SUBMISSION_FAILED = "TEAM_SUBMISSION_FAILED";
export const TEAM_SUBMISSION_ERROR = "TEAM_SUBMISSION_ERROR";
