export const FETCH_SCHEMA_LOADING = "FETCH_SCHEMA_LOADING";
export const FETCH_SCHEMA_SUCCESS = "FETCH_SCHEMA_SUCCESS";
export const FETCH_SCHEMA_ERROR = "FETCH_SCHEMA_ERROR";
export const FETCHED_NO_SCHEMA = "FETCHED_NO_SCHEMA";
