export const EMAIL_VERIFY_LOADING = "EMAIL_VERIFY_LOADING";
export const EMAIL_VERIFY_SUCCESS = "EMAIL_VERIFY_SUCCESS";
export const EMAIL_VERIFY_ERROR = "EMAIL_VERIFY_ERROR";
export const EMAIL_VERIFY_FAILURE ="EMAIL_VERIFY_FAILURE";
